In [1]:
import DeepNeuralNetworkSleep.hdf5_files.datasets_extraction as DE
import os
import numpy as np
import h5py

## Load and prepare files

In [2]:
file = 'D:/EEG_Data_stage/datasets/intra_cranial_dataset.h5'
output = 'D:/EEG_Data_stage/datasets/'



## Define the state names and amounts per state to use in training

In [3]:
training_nights = ["2_night1", "2_night2", "7_night1", "15_night1", "28_night2", "31_night1", "87_night1"]
test_nights = ["7_night2", "15_night2"]

with h5py.File(file, 'r') as f:
    array_scores = np.array([])
    for group_name in f.keys():
        if group_name in training_nights:
            group = f[group_name]
            array_scores = np.concatenate((array_scores, group['Mapped_scores'][:]), axis=0)

train_values, train_counts = np.unique(array_scores, return_counts=True)

print(train_values)   # all unique values
print(train_counts)   # how many times each appears

with h5py.File(file, 'r') as f:
    array_scores = np.array([])
    for group_name in f.keys():
        if group_name in test_nights:
            group = f[group_name]
            array_scores = np.concatenate((array_scores, group['Mapped_scores'][:]), axis=0)

test_values, test_counts = np.unique(array_scores, return_counts=True)

print(test_values)
print(test_counts)

[0. 1. 2. 3. 4.]
[11890   918 10978  2053  4035]
[0. 1. 2. 3. 4.]
[3187  162 2401  579  721]


In [4]:
training_features, training_scores = DE.training_dataset(
    file, [0, 1, 2, 3, 4], [1377, 918, 918, 918, 459], training_nights)
test_features, test_scores = DE.training_dataset(file, [0, 1, 2, 3, 4], [243, 162, 162, 162, 81], test_nights)


In [5]:
np.save(os.path.join(output, 'training_features'), training_features)
np.save(os.path.join(output, 'training_scores'), training_scores)
np.save(os.path.join(output, 'test_features'), test_features)
np.save(os.path.join(output, 'test_scores'), test_scores)